### ISSUE TITLE
Invalid number of arguments!

### ISSUE THREAD

**Issue by abhishektiwarijr** [Eyallotan/GC_Simulator#1]
Hi there
I tried running this simulator after proper setup from examples on my Ubuntu 20.04.3 LTS.
i.e. ./Simulator 12 7 4 4096 100000 uniform greedy

Getting error response

Invalid number of arguments!
Garbage collection (GC) manual: 
These are the parameters you must set for each simulation:
1. Number of physical blocks (T).
2. Number of logical blocks (U).
3. Pages per block (Z).
4. Page size (in bytes).
5. Number of pages (N).
6. Data distribution.
7. GC algorithm.
8. Optional parameter: Filename to redirect output to.
For data distribution parameter choose between uniform or hot_cold. If you choose hot/cold distribution, 
you will be asked to choose the hot page percentage and the probability for a hot page.
For GC algorithm choose between the following:
1. greedy.
2. greedy_lookahead.
3. writing_assignment (initial version).
4. generational. If you choose this option you will be prompt to choose the number of generations. 
Make sure that the number of generations is always larger then T-U (this will be enforced by the simulator).
If you choose number of generations to be 0, the simulator will choose the optimized parameter based on the OP (over provisioning).

Please help me out.

**Comment by Eyallotan** [comment]
Hello my friend, 
You are right, the command line options were updated but the documentation did not reflect the changes. 
You are now required to add another command line argument stating if you would like to use a window of future writes in your simulation. Please pull the recent updates and use the updated documentation and readme.md. 

For you example you should run ./Simulator 12 7 4 4096 100000 window_off uniform greedy
and it should work.

If you have any further questions please feel free to ask.
